version: '1.0.0'

services:
  express-app:
    image: node-server
    build:
      context: .
      dockerfile: Dockerfile
  mongodb:
    image: mongodb/mongodb-community-server
    ports: 
      - "27017:27017"